### ISSUE TITLE
Unique characters causes errors in qsMask function

### ISSUE THREAD

**Issue by noahwiener** [gwpmad/mask-deep#1]
We've seen maskdeep returning an error when `value` includes non-standard characters in this function: https://github.com/gwpmad/mask-deep/blob/master/src/mask-deep.js#L56

Solved temporarily by wrapping maskdeep in a try/catch, but it'd be better to be handled within the code linked above.

**Comment by gwpmad** [comment]
Issue solved in new version (3.0.4)
